"""Add subreddit field to DataReddit

Revision ID: 2715653edffd
Revises: 1d5a2207257c
Create Date: 2023-09-06 15:27:56.733592

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2715653edffd'
down_revision = '1d5a2207257c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_reddit', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subreddit', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_reddit', schema=None) as batch_op:
        batch_op.drop_column('subreddit')

    # ### end Alembic commands ###
