"""add fields to ratings

Revision ID: 55547e900243
Revises: 7054d3fa74f4
Create Date: 2023-08-13 17:05:27.694370

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55547e900243'
down_revision: Union[str, None] = '7054d3fa74f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('story_ratings', sa.Column('prompt', sa.String(), nullable=False))
    op.add_column('story_ratings', sa.Column('model_name', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('story_ratings', 'model_name')
    op.drop_column('story_ratings', 'prompt')
    # ### end Alembic commands ###
