"""story should cascade deletes

Revision ID: 7054d3fa74f4
Revises: 9ec0b549c948
Create Date: 2023-08-12 20:31:53.766019

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7054d3fa74f4'
down_revision: Union[str, None] = '9ec0b549c948'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
