"""Add DataReddit table

Revision ID: 717ae8112a61
Revises: a59dc43bd894
Create Date: 2023-09-05 21:06:04.826344

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '717ae8112a61'
down_revision = 'a59dc43bd894'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_reddit',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('text', sa.String(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('data_reddit')
    # ### end Alembic commands ###
