"""add story ratings

Revision ID: 8628cc4aba67
Revises: 3b4204004410
Create Date: 2023-08-12 12:50:41.450330

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8628cc4aba67'
down_revision: Union[str, None] = '3b4204004410'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('story_ratings',
    sa.Column('story_id', sa.UUID(), nullable=False),
    sa.Column('rating_type', sa.String(), nullable=False),
    sa.Column('rating', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ),
    sa.PrimaryKeyConstraint('story_id', 'rating_type', 'rating')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('story_ratings')
    # ### end Alembic commands ###
