"""add fields to ratings

Revision ID: f23ad420af68
Revises: 55547e900243
Create Date: 2023-08-13 17:09:17.178824

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f23ad420af68'
down_revision: Union[str, None] = '55547e900243'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('story_ratings', sa.Column('model_output', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('story_ratings', 'model_output')
    # ### end Alembic commands ###
